### ISSUE TITLE
Restart ARMA machine

### ISSUE THREAD

**Issue by ProjectAwesomeGaming** [ProjectAwesomeGaming/Community-Feedback#20]
ARMA server wouldn't boot up tonight. I tried to restart using console, didn't work. ARMA was in background processes (in task manager) and wouldn't close using the console or by me trying to "end task". I didn't know what else to do so I restarted the machine to see if that would help. It helped.

**Comment by linkspec** [comment]
Server had been started outside of the normal monitoring script in an attempt to resolve another issue that appeared when I wasn't available, which is why it wouldn't respond to the control panel. Restarting it will have automatically set it correct.

Am working on documentation to cover the knowledge gap that allowed this to crop up.
