### ISSUE TITLE
UI Issues

### ISSUE THREAD

**Issue by Foodstamp001** [ProjectAwesomeGaming/Community-Feedback#36]
Names still aren't showing up when you hover over people, and UI elements are missing such as altitude when HALO dropping

**Comment by jonas232** [comment]
Vanilla HALO or 3rd party scripted HALO? @Foodstamp001

**Comment by Hamster2k** [comment]
First half of your issue is a duplicate of #30 and fixed (please keep issues seperate from now on).

What other UI elements are missing? Which mission did it happen on? Liberation deploys their own cba mission config that overrides a lot of our server config and I don't want to force override everything in our settings. Is the lacking altitude gauge a big deal?

**Comment by Foodstamp001** [comment]
It's not mission specific. It's happening in D. recon and lib. Altitude and airspeed are very important when jumping...

**Comment by Hamster2k** [comment]
https://github.com/acemod/ACE3/pull/5836

**Comment by Hamster2k** [comment]
The setting to hide the altimeter is currently turned off, but can be overridden by client and mission. Please check your personal and/or the mission settings!

**Comment by Hamster2k** [comment]
I just loaded up Sahrani Lib and I see both speed and altitude. Seems like you have it set to hidden in your personal settings :D
