### ISSUE TITLE
Chat disabled by wolf pack missions

### ISSUE THREAD

**Issue by linkspec** [ProjectAwesomeGaming/Community-Feedback#7]

**Comment by Hamster2k** [comment]
I'd rather not change all the wolf pack missions when all you need to do to log in is go to map screen and switch to global chat.

**Comment by linkspec** [comment]
Is it your mission? The report I had was that restarting the server didn't return the chat ability, so I need to know which function was used to disable the chat.

**Comment by Hamster2k** [comment]
It's not my mission, but I know how to disable chat channels. https://community.bistudio.com/wiki/Description.ext#disableChannels

One of the chat channels is disabled on that mission, using another channel to log in as admin works (but you need to go to map screen for that because on the slotting screen you only have group channel). Changing to another mission removes the restriction again.

**Comment by ProjectAwesomeGaming** [comment]
Why do we need chat on a server that doesn't allow side chat?

@Hamster2k

**Comment by Hamster2k** [comment]
Server chat commands:

https://community.bistudio.com/wiki/Multiplayer_Server_Commands#Commands

You can't log in as admin without a chat window.

**Comment by ProjectAwesomeGaming** [comment]
shiiiiiiiiiiiiiiiiiiiiiiiiiit

**Comment by linkspec** [comment]
Ok, I'm happy that this issue isn't as originally advised, so closing.
